fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
